<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="shyams-mbp" name="com.cashe.mobile.tests.NewCustomerLoanRequest" tests="3" failures="1" timestamp="06 Jul 2018 08:29:37 GMT" time="1611.256" errors="0">
  <testcase name="tt" time="788.140" classname="com.cashe.mobile.tests.NewCustomerLoanRequest"/>
  <testcase name="tt" time="381.410" classname="com.cashe.mobile.tests.NewCustomerLoanRequest">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.fail(Assert.java:100)
	at com.cashe.mobile.tests.NewCustomerLoanRequest.tt(NewCustomerLoanRequest.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- tt -->
  <testcase name="tt" time="441.706" classname="com.cashe.mobile.tests.NewCustomerLoanRequest"/>
</testsuite> <!-- com.cashe.mobile.tests.NewCustomerLoanRequest -->
