<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Aeries-HF61NJ2" name="com.cashe.base.pCloudyTest" tests="1" failures="0" timestamp="01 Dec 2017 06:00:57 GMT" time="72.693" errors="1">
  <testcase name="runExecutionOnPCloudy" time="72.693" classname="com.cashe.base.pCloudyTest">
    <error type="com.ssts.pcloudy.exception.ConnectError" message="cannot find the token">
      <![CDATA[com.ssts.pcloudy.exception.ConnectError: cannot find the token
	at com.ssts.pcloudy.appium.AppiumApi.extendSession(AppiumApi.java:205)
	at com.ssts.pcloudy.appium.AppiumApi.releaseSession(AppiumApi.java:177)
	at com.ssts.pcloudy.appium.AppiumApi.releaseSession(AppiumApi.java:181)
	at com.ssts.pcloudy.appium.PCloudyAppiumSession.releaseSessionNow(PCloudyAppiumSession.java:24)
	at com.cashe.base.pCloudyTest.getTestCaseClass(pCloudyTest.java:98)
	at com.cashe.base.pCloudyTest.runExecutionOnPCloudy(pCloudyTest.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- runExecutionOnPCloudy -->
</testsuite> <!-- com.cashe.base.pCloudyTest -->
